### ISSUE TITLE
[Question]: What the purpose of response sometimes returning nil when an error occurs

### ISSUE THREAD

**Issue by sakamoto-souta** [acompany-develop/QuickMPC#158]
Some requests do not return error when the error occurs. (ex:https://github.com/acompany-develop/QuickMPC/blob/1315414c5e83647bbd131ef9f56a60a66f7f71c8/packages/server/manage_container/server/libc_to_manage_container/L2m.go#L114-L121)

I think it can be written simply such as `return &empty.Empty{}, err`.

I would like to know if there is a reason for the current implementation.

**Comment by mdonaka** [comment]
@sakamoto-souta 
There is probably no deep reason.
I guess I thought these didn't have to return an error because these put the error in the `message`.
This `message' is not used now, so there seems to be no reason other than a vestige of the past.
I don't know what the intention of `message` was, but I thought the format you described was nice and clean.
